MVCBookstore/Models/Bookinsert.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCBookstore.Models
{
    public class Bookinsert
    {
        [Required(ErrorMessage ="Enter name")]
        public string bookname { get; set; }

        [Required(ErrorMessage = "Enter author")]
        public string author { get; set; }

        
        public string image { get; set; }

        [Required(ErrorMessage = "Enter price")]
        public int price { get; set; }

        public string msg { get; set; }
    }
}

MVCBookstore/Models/UserPwd.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCBookstore.Models
{
    public class UserPwd
    {

        public string oldpassword { set; get; }
        [Required(ErrorMessage ="enter password")]
        public string newpassword { set; get; }
        [Compare("newpassword",ErrorMessage ="password mismatch")]
        public string confirmpassword { set; get; }

        public string msg { set; get; }

    }
}

MVCBookstore/Models/adminlogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCBookstore.Models
{
    public class adminlogin
    {
        [Required(ErrorMessage ="enter username")]
        public string Username { get; set; }
        [Required(ErrorMessage ="enter password")]
        public string Password { get; set; }
        public string msg { get; set; }

    }
}

MVCBookstore/Models/adminregister.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCBookstore.Models
{
    public class adminregister
    {
        [Required(ErrorMessage ="Enter Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Enter address")]
        public string Address { get; set; }
        [EmailAddress(ErrorMessage ="enter valid email")]
        public string Email { get; set; }
        [Required(ErrorMessage ="enter username")]
        public string Username { get; set; }
        [Required(ErrorMessage ="enter password")]
        public string Password { get; set; }
        [Compare("Password",ErrorMessage ="password mismatch")]
        public string confirmpassword { get; set; }
        public string msg { get; set; }
    }
}

MVCBookstore/Models/displayall.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBookstore.Models
{
    public class displayall
    {
        public string bookname { get; set; }
        public string author { get; set; }
        public string image { get; set; }
        public int price { get; set; }
    }
}

MVCBookstore/Controllers/AddBookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBookstore.Models;

namespace MVCBookstore.Controllers
{
    public class AddBookController : Controller
    {
        MVCProjectEntities dbobj = new MVCProjectEntities();
        // GET: AddBook
        public ActionResult Book_load()
        {
            return View();
        }

        public ActionResult Book_click(Bookinsert objcls,HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file.ContentLength > 0)
                {
                    string fname = Path.GetFileName(file.FileName);
                    var s = Server.MapPath("~/PHS");
                    string pa = Path.Combine(s, fname);
                    file.SaveAs(pa);

                    var fullpath = Path.Combine("~\\PHS", fname);
                    objcls.image = fullpath;
                }
                dbobj.sp_bookadd(objcls.bookname, objcls.author, objcls.image, objcls.price);
                objcls.msg = "book added";
                return View("Book_load", objcls);
            }

            return View("Book_load",objcls);
        }
    }
}

MVCBookstore/Controllers/AdminRegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBookstore.Models;

namespace MVCBookstore.Controllers
{
    public class AdminRegisterController : Controller
    {
        MVCProjectEntities dbobj = new MVCProjectEntities();
        // GET: AdminRegister
        public ActionResult register_pageload()
        {
            return View();
        }

        public ActionResult register_click(adminregister objcls)
        {
            if (ModelState.IsValid)
            {
                dbobj.sp_regadmin(objcls.Name, objcls.Address, objcls.Email, objcls.Username, objcls.Password);
                objcls.msg = "successfully Registered";
                return View("register_pageload", objcls);

            }
            return View("register_pageload",objcls);
        }
    }
}

MVCBookstore/Controllers/ChangePwdController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBookstore.Models;
namespace MVCBookstore.Controllers
{
    public class ChangePwdController : Controller
    {
        MVCProjectEntities dbobj = new MVCProjectEntities();
        // GET: ChangePwd
        public ActionResult pwd_load()
        {
            return View();
        }
        public ActionResult pwd_click(UserPwd objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status",typeof(int));
                dbobj.sp_pwdchange(Session["uname"].ToString(), objcls.oldpassword, objcls.newpassword, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    objcls.msg = "password changed";
                    return View("pwd_load", objcls);
                }
                else
                {
                    objcls.msg = "invalid password";
                    return View("pwd_load", objcls);
                }

            }
            return View("pwd_load",objcls);
        }
    }
}

MVCBookstore/Controllers/DBLoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBookstore.Models;
namespace MVCBookstore.Controllers
{
    public class DBLoginController : Controller
    {
        MVCProjectEntities dbobj = new MVCProjectEntities();
        // GET: DBLogin
        public ActionResult Login_pageload()
        {
            return View();
        }

        public ActionResult Home(book ob)
        {
             
            //var list = new List<book>();
            return View(dbobj.books.ToList());
        }

        public ActionResult Login_click(adminlogin objcls)
        {
            if (ModelState.IsValid)
            {
                ObjectParameter op = new ObjectParameter("status", typeof(int));
                dbobj.sp_login(objcls.Username, objcls.Password, op);
                int val = Convert.ToInt32(op.Value);
                if (val == 1)
                {
                    Session["uname"] = objcls.Username;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.Clear();
                    objcls.msg = "invalid login";
                    return View("Login_pageload", objcls);
                }
            }
            return View("Login_pageload",objcls);
        }
    }
}

MVCBookstore/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCBookstore.Models;


namespace MVCBookstore.Controllers
{
    public class DisplayController : Controller
    {
        MVCProjectEntities dbobj = new MVCProjectEntities();
        // GET: Display
        public ActionResult display_load(book ob)
        {
            return View();
        }
    }
}

MVCBookstore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCBookstore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCBookstore/Views/AddBook/Book_load.cshtml
@model MVCBookstore.Models.Bookinsert
@{
    ViewBag.Title = "Book_load";
}

<h2>Add Books</h2>
<div>
    @using (Html.BeginForm("Book_click", "AddBook", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div>
            <label>Book name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.bookname)
            @Html.ValidationMessageFor(m => m.bookname)
        </div>

        <div>
            <label>Book author:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.author)
            @Html.ValidationMessageFor(m => m.author)
        </div>

        <div>
            <label>image</label>
        </div>
        <div>
            @Html.TextBox("file", "", new { Type = "file" })
        </div>

        <div>
            <label>price</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.price)
            @Html.ValidationMessageFor(m => m.price)
        </div>
        <div>
            @Html.DisplayFor(m => m.msg)
        </div>
        <div>
            <input type="submit" value="Add"/>
        </div>
        <div>
            @Html.ActionLink("Back to Home", "Home", "DBLogin")
        </div>
    }
</div>

MVCBookstore/Views/AdminRegister/register_pageload.cshtml
@model MVCBookstore.Models.adminregister
@{
    ViewBag.Title = "register_pageload";
}

<h2>Register</h2>
<div>
    @using(Html.BeginForm("register_click", "AdminRegister", FormMethod.Post))
            {
    <table border-spacing:10px>
        <tr>
            <th><label>Name:</label></th>
            <td>
                @Html.TextBoxFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name)
            </td>

        </tr>
        <tr></tr>
        <tr>
            <th><label>Address:</label></th>
            <td>
                @Html.TextBoxFor(m => m.Address)
                @Html.ValidationMessageFor(m => m.Address)
            </td>
        </tr>
        <tr></tr>
        <tr>
            <th><label>Email:</label></th>
            <td>
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email)
            </td>
        </tr>
        <tr></tr>
        <tr>
            <th><label>Username:</label></th>
            <td>
                @Html.TextBoxFor(m => m.Username)
                @Html.ValidationMessageFor(m => m.Username)
            </td>
        </tr>
        <tr></tr>
        <tr>
            <th><label>Password:</label></th>
            <td>
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </td>
        </tr>
        <tr></tr>
        <tr>
            <th><label>Confirm Password:</label></th>
            <td>
                @Html.PasswordFor(m => m.confirmpassword)
                @Html.ValidationMessageFor(m => m.confirmpassword)
            </td>
        </tr>

    </table>
    <div>
        <input type="submit" value="Register" />
        @Html.DisplayFor(m => m.msg)
    </div>
            }
</div>

MVCBookstore/Views/ChangePwd/pwd_load.cshtml
@model MVCBookstore.Models.UserPwd
@{
    ViewBag.Title = "pwd_load";
}

<h2>change password</h2>
<div>
    @using (Html.BeginForm("pwd_click", "ChangePwd", FormMethod.Post))
    {
        <div>
            <label>Current password</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.oldpassword)
        </div>

        <div>
            <label>new password</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.newpassword)
            @Html.ValidationMessageFor(m => m.newpassword)
        </div>

        <div>
            <label>confirm password</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.confirmpassword)
            @Html.ValidationMessageFor(m => m.confirmpassword)
        </div>
        <div>
            <input type="submit" value="Reset password" />
            @Html.DisplayFor(m => m.msg)
        </div>
        <div>
            @Html.ActionLink("Back to Home", "Home", "DBLogin")
        </div>
    }
</div>

MVCBookstore/Views/DBLogin/Home.cshtml
@model IEnumerable<MVCBookstore.book>
@{
    ViewBag.Title = "Home";
}

<h3>Welcome</h3>


<div>
    @using (Html.BeginForm("Home", "DBLogin", FormMethod.Get))
    {

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(m => m.bookname)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.author)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.image)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.price)
                </th>
                @*<th>
                        @Html.DisplayNameFor(m => m.Photo)
                    </th>*@
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.bookname)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.author)
                    </td>
                    <td>
                        <img src="@Url.Content(item.image)" alt="image" height="150px" width="150px" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.price)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>*@

                </tr>
            }
        </table>
    }
</div>
<div>
    @Html.ActionLink("Add Books", "Book_load", "AddBook")
</div>

<div>
    @Html.ActionLink("change password", "pwd_load", "ChangePwd")
</div>

MVCBookstore/Views/DBLogin/Login_pageload.cshtml
@model MVCBookstore.Models.adminlogin
@{
    ViewBag.Title = "Login_pageload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>
<div>
    @using(Html.BeginForm("Login_click", "DBLogin", FormMethod.Post))
            {
                <div>
                    <table>
                        <tr>
                            <th><label>UserName:</label></th>
                            <td>
                                @Html.TextBoxFor(m => m.Username)
                                @Html.ValidationMessageFor(m => m.Username)
                            </td>
                        </tr>
                        <tr>
                            <th><label>password:</label></th>
                            <td>
                                @Html.PasswordFor(m => m.Password)
                                @Html.ValidationMessageFor(m => m.Password)
                            </td>
                        </tr>
                        <tr>
                            
                        </tr>
                    </table>
                    <div>
                        <input type="submit" value="Login" />
                        @Html.DisplayFor(m => m.msg)
                        @Html.ActionLink("Register", "register_pageload", "AdminRegister")
                    </div>

                </div>
            }
</div>

MVCBookstore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCBookstore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCBookstore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCBookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>